CREATE DATABASE dbtoko;

CREATE TABLE "produk" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kategori_id" integer,
  "nama" varchar,
  "harga" integer,
  "stok" integer
);

CREATE TABLE "kategori" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_kategori" varchar
);

ALTER TABLE "produk" ADD FOREIGN KEY ("kategori_id") REFERENCES "kategori" ("id");


INSERT INTO kategori(nama_kategori) 
VALUES 
('Mainan Anak-anak'),
('Mainan Edukatif'),
('Mainan Elektronik');

INSERT INTO produk(nama, harga, stok, kategori_id)
VALUES
('Boneka Barbie', 50000, 100, 1),
('Puzzle Alfabet', 20000, 80, 2),
('Robot Transformers', 80000, 50, 3),
('Mobil Remote Control', 70000, 60, 3),
('Bola Plastik', 10000, 120, 1);

SELECT * from produk;
SELECT * from kategori;

UPDATE produk
SET harga = 100000
WHERE produk.id = 4

INSERT INTO produk(nama, harga, stok, kategori_id)
VALUES
('Boneka Elsa Frozen', 50000, 5, 4)

DELETE FROM produk
WHERE id = 6

INSERT INTO kategori(nama_kategori)
VALUES
('Mainan Laki-Laki')

INSERT INTO kategori(nama_kategori)
VALUES
('Mainan Laki-Laki')

DELETE FROM kategori 
WHERE kategori.id = 5;

UPDATE kategori
SET nama_kategori = 'Mainan Remaja'
WHERE kategori.id = 4

UPDATE produk
SET kategori_id = 4
WHERE id = 4

SELECT * from kategori
WHERE kategori.id = 2;

SELECT
produk.id AS id,
produk.nama AS nama,
produk.harga AS harga,
produk.stok AS stok,
kategori.nama_kategori AS nama_kategori
FROM
produk
INNER JOIN kategori ON kategori_id = kategori.id

